<ActionsView@GridLayout>:
    rows: 3
    padding: [dp(5),dp(5),dp(5),dp(5)]
    default_size_hint: 1, None
    GridLayout:
        cols: 2
        size_hint_y: None
        height: dp(25)
        Button:
            text: "Desktop Settings"
        Button:
            text: "Custom Scripts"
    Label:
        text: "Status Output"
    Label:
        size_hint_y: None
        height: dp(25)
        text: "status bar <should be an image>"